name: Hola mundo
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer jobM
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo GitHub main DevOps
      run: |
        echo $MI_VARIABLE.
